[package]
name = "rssrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "1.0.4"
http = "0.1.5"
feed-rs = "1.0.0"
serde = "1.0.136"
serde_yaml = "0.8.23"
